name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.6.2

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['staging', 'prod']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ID }}
        run: echo "::add-mask::$AWS_ACCESS_KEY_ID" && echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init
        run: |
          cd terraform/${{ matrix.environment }}
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/${{ matrix.environment }}
          terraform plan -var-file=input.tf -out=plan.out

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: terraform/${{ matrix.environment }}/plan.out

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      url: ${{ steps.deploy.outputs.url }}
    strategy:
      matrix:
        environment: ['staging', 'prod']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ID }}
        run: echo "::add-mask::$AWS_ACCESS_KEY_ID" && echo "::add-mask::$AWS_SECRET_ACCESS_KEY"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: terraform/${{ matrix.environment }}

      - name: Terraform Apply
        run: |
          cd terraform/${{ matrix.environment }}
          terraform apply plan.out
