name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.6.2
  AWS_REGION: "eu-west-2"

jobs:
  terraform-plan-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          cd terraform/staging
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/staging
          terraform plan -var="github_sha=${{ github.sha }}" -out=plan.out

      - name: Archive Terraform data
        run: |
          tar -czvf terraform-staging-data.tar.gz -C terraform/staging . 

      - name: Upload Terraform data
        uses: actions/upload-artifact@v2
        with:
          name: terraform-data-staging
          path: terraform-staging-data.tar.gz

  terraform-apply-staging:
    needs: terraform-plan-staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform data
        uses: actions/download-artifact@v2
        with:
          name: terraform-data-staging
          path: .

      - name: Unarchive Terraform data
        run: |
          tar -xzvf terraform-staging-data.tar.gz -C terraform/staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Apply
        run: |
          cd terraform/staging
          terraform apply plan.out

  terraform-plan-prod:
    needs: terraform-apply-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          cd terraform/prod
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/prod
          terraform plan -var="github_sha=${{ github.sha }}" -out=plan.out

      - name: Archive Terraform data
        run: |
          tar -czvf terraform-prod-data.tar.gz -C terraform/prod . 

      - name: Upload Terraform data
        uses: actions/upload-artifact@v2
        with:
          name: terraform-data-prod
          path: terraform-prod-data.tar.gz

  terraform-apply-prod:
    needs: terraform-plan-prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform data
        uses: actions/download-artifact@v2
        with:
          name: terraform-data-prod
          path: .

      - name: Unarchive Terraform data
        run: |
          tar -xzvf terraform-prod-data.tar.gz -C terraform/prod

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Apply
        run: |
          cd terraform/prod
          terraform apply plan.out
